In [1]:
# What  is pandas.
# Pandas = Python Library for data manipulation and analysis visualization built around frame (2d labeled table structure).
# 1.Dataframe = table-like structure with rows/columns,supports SQL-like indexing, filtering, slicing.
#2. Data Cleaning =  Handle missing values(NaN), duplicates , dtype conversion via dropna(),fillna(),astype()
#3.GroupBy & aggregation = groupby(),pivot_table() for last aggar(sum/mean/count by category)
#4. Ecosystem integrate = works seamlessly with NumPy, Matplotlib, Scikit-Learn and SQL - Core of any DS pipelines

In [3]:
import pandas as pd


data= {
    "name":["Aman","Anuj","ALok"],
    "age":[25,22,18],
    "city":["Gurgaon","Delhi","Bihar"]
}

df=pd.DataFrame(data)
df

   name  age     city
0  Aman   25  Gurgaon
1  Anuj   22    Delhi
2  ALok   18    Bihar

In [4]:
# view basic info of your dataset:
df.head()
df

   name  age     city
0  Aman   25  Gurgaon
1  Anuj   22    Delhi
2  ALok   18    Bihar

In [5]:
#shape
df.shape  #(rows, columns)
df

   name  age     city
0  Aman   25  Gurgaon
1  Anuj   22    Delhi
2  ALok   18    Bihar

In [ ]:
# select rows and columns

d=(df[['name','city']])
d

   name     city
0  Aman  Gurgaon
1  Anuj    Delhi
2  ALok    Bihar

In [6]:
Employee={
    "I'd":[10,11,12,13,14],
    "Name":["Aman","Amar","Anup","Alok","Arun"],
    "Age":[22,24,26,28,30],
    "Salary":[8000,10000,12000,14000,16000],
    "City":["Bihar","MP","UP","Delhi","Noid"]
}
table=pd.DataFrame(Employee)
table

   I'd  Name  Age  Salary   City
0   10  Aman   22    8000  Bihar
1   11  Amar   24   10000     MP
2   12  Anup   26   12000     UP
3   13  Alok   28   14000  Delhi
4   14  Arun   30   16000   Noid

In [7]:
table.tail(2)

   I'd  Name  Age  Salary   City
3   13  Alok   28   14000  Delhi
4   14  Arun   30   16000   Noid

In [8]:
table['Name'] = table['Name'].apply(lambda x: x.upper())
table

   I'd  Name  Age  Salary   City
0   10  AMAN   22    8000  Bihar
1   11  AMAR   24   10000     MP
2   12  ANUP   26   12000     UP
3   13  ALOK   28   14000  Delhi
4   14  ARUN   30   16000   Noid

In [9]:
table['Name'] = table['Name'].apply(lambda x: x.lower())
table

   I'd  Name  Age  Salary   City
0   10  aman   22    8000  Bihar
1   11  amar   24   10000     MP
2   12  anup   26   12000     UP
3   13  alok   28   14000  Delhi
4   14  arun   30   16000   Noid