In [ ]:
#finding missing data
import numpy as np 
import pandas as pd

data = {
    'A': [1, 2, np.nan, 4, 5], #np.nan means null value
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
# df
# df.isna() #how to find null value
# df.isna().sum() #count null values
# df.isna().any() #if there is any missing values
df.dropna()  # when we are removing the missing data it is work on row basiss.
# df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0

In [9]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
#filling the missing data

df.fillna(1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

In [11]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0